remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/leap-day@v0.2.0

title: SimpliCity city simulation game rooted in the original SimCity
description: A calm, classic city simulation game for relaxed play.
